name: releaseBuild

on: release

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compile and release
        uses: mmalcek/go-release.action@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_NAME: xmltransform
          GOARCH: amd64
          GOOS: windows
          EXTRA_FILES: "README.md LICENSE lua/json.lua lua/functions.lua"
