name: releaseBuild

on: release

jobs:
  update-mkdocs:
    name: Deploy mkdocs documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs
      - run: mkdocs gh-deploy --force
  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: compile and release
        uses: mmalcek/go-release.action@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_NAME: xmltransform
          GOARCH: amd64
          GOOS: windows
          EXTRA_FILES: "README.md LICENSE testdata.xml template.tmpl lua/json.lua lua/functions.lua"
