name: releaseBuild

on: release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: compile and release - windows/amd64
        uses: spetr/go-release.action@v1.0.3
        env:
          PROJECT_NAME: xmltransform
          GOARCH: amd64
          GOOS: windows
          EXTRA_FILES: "README.md LICENSE lua/functions.lua lua/json.lua"
